# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pkgbuild-git:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pkg-git

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: 'cvc5-git'
      
      
      - name: Verify SRCINFO
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'srcinfo'
          pkgname: 'cvc5-git'
      
      
      # - name: Build
      #   uses: 2m/arch-pkgbuild-builder@v1.16
      #   with:
      #     target: 'pkgbuild'
      #     pkgname: 'cvc5-git'
      
      - name: Build & Run
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'run'
          pkgname: 'cvc5-git'
          command: 'cvc5 ../test.smt'

 pkgbuild-bin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pkg-bin

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: 'cvc5-bin'
      
      
      - name: Verify SRCINFO
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'srcinfo'
          pkgname: 'cvc5-bin'
      
      
      # - name: Build
      #   uses: 2m/arch-pkgbuild-builder@v1.16
      #   with:
      #     target: 'pkgbuild'
      #     pkgname: 'cvc5-git'
      
      - name: Build & Run
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'run'
          pkgname: 'cvc5-bin'
          command: 'cvc5 ../test.smt'

